---
version: "2"
plugins:
  markdownlint:
    enabled: true
  scss-lint:
    enabled: true
    checks:
      ColorVariable:
        enabled: false
      UrlFormat:
        enabled: false
  eslint:
    enabled: true